version: "3.8"
services:
  eureka-server:
    build: ./EurekaServer
    image: mahbuhrer/eureka-server:1.0  # Usando a tag 1.0 e vinculando ao seu repositório Docker Hub
    container_name: eureka-server
    ports:
      - "8762:8761"
    networks:
      - infnet_network

  veiculo-service:
    build: ./Q02
    image: mahbuhrer/veiculo-service:1.0  # Usando a tag 1.0 e vinculando ao seu repositório Docker Hub
    container_name: veiculo-service
    ports:
      - "9085:8085"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8761/eureka
    networks:
      - infnet_network

networks:
  infnet_network:
    driver: bridge
