version: "3.8"
services:
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8762:8761"  # Alterando para usar a porta 8762 no host
    networks:
      - infnet_network

  veiculo-service:
    build: ./Q02
    container_name: veiculo-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_SERVER_URI=http://eureka-server:8762/eureka  # Atualizando o URI com a nova porta
    networks:
      - infnet_network

networks:
  infnet_network:
    driver: bridge
