name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Q02/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test project
        run: mvn clean verify
        working-directory: ./Q02

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: Q02/target/surefire-reports

      - name: Archive build output
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: Q02/target/*.jar

      - name: Report test results in GitHub
        if: failure()
        run: cat Q02/target/surefire-reports/*.txt
