name: Deploy Q02 to Kubernetes

on:
  push:
    branches:
      - deployment  # Branch destinada para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('Q02/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Q02 with Maven
        working-directory: ./Q02
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot-q02:latest ./Q02
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-q02:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy Q02 to Kubernetes
        run: |
          kubectl set image deployment/spring-boot-q02 spring-boot-q02=${{ secrets.DOCKER_USERNAME }}/spring-boot-q02:latest
          kubectl rollout status deployment/spring-boot-q02  # Verificar o status do deployment
